### ISSUE TITLE
Add support for the GitHub security advisory endpoint in orgs and repos

### ISSUE THREAD

**Issue by cartersocha** [shurcooL/githubv4#116]
The OTel community would like to build a governance dashboard that monitors open incidents and various attributes around that data like when an incident was opened, the relevant repo etc. 

https://docs.github.com/en/rest/security-advisories/repository-advisories?apiVersion=2022-11-28

**Comment by dmitshur** [comment]
The page you linked to is a part of the GitHub REST API. If that's what you're looking for, see https://pkg.go.dev/github.com/google/go-github/v55/github#SecurityAdvisoriesService. This repository has a client for the GitHub GraphQL API only.
