### ISSUE TITLE
How to encode GraphQL Aliases

### ISSUE THREAD

**Issue by davidoram** [shurcooL/githubv4#39]
Hi, I'm trying to figure out how to encode GraphQL aliases (https://graphql.github.io/learn/queries/#aliases) using this library.

I'm trying to encode something like this query:

```
{
  repository(owner: "davidoram", name: "gittest") {
    nameWithOwner
    tags: refs(refPrefix: "refs/tags/", last: 30, orderBy: {field: TAG_COMMIT_DATE, direction: DESC}) {
      edges {
        tag: node {
          name
          target {
            sha: oid
          }
        }
      }
    }
  }
}
```

.. in particular I haven't figured out how to encode the `tags: refs` alias as a go struct with the appropriate `graphql` struct tag?

**Comment by dmitshur** [comment]
@davidoram Thanks for asking. Aliases are supported, but I haven't documented them yet (see #22). I hope to fix that soon.

The answer is as follows. A GraphQL query like this:

```GraphQL
query {
  aliasGoesHere: repository(owner: "golang", name: "go") {
    nameWithOwner
    description
  }
}
```

Would be implemented with the following Go query struct:

```Go
var query struct {
	AliasGoesHere struct {
		NameWithOwner string
		Description   string
	} `graphql:"aliasGoesHere: repository(owner: \"golang\", name: \"go\")"`
}
```

Basically, you just put the alias prefix at the beginning of the `graphql` tag. Let me know if that makes sense.

**Comment by davidoram** [comment]
Thanks @dmitshur, that worked like a charm 👍 .  

If it helps anyone else - I have another example [here](https://github.com/davidoram/ght/blob/feature/v4api/main.go#L128) where I retrieve the `tags` for a `repository`
