### ISSUE TITLE
Enable starfox preview

### ISSUE THREAD

**Issue by brejoc** [shurcooL/githubv4#44]
I would like to [enable the starfox-preview](https://developer.github.com/changes/2018-09-05-project-card-events/). In order to do that, a header must be set like this: `eq.Header.Add("Accept", "application/vnd.github.starfox-preview")`

I tested this with setting it in `ctxhttp.go`, which is of course only good for testing. Where would be the right place to accomplish this? The `Post()` func in `ctxhttp.go` immediately returns the response with the execution of `Do()`. Thx!

**Comment by dmitshur** [comment]
The tracking issue for schema preview support is #34. It's not implemented yet, see the discussion there for more information.

**Comment by brejoc** [comment]
Thanks for your answer, @dmitshur. Then let's close this one.
