### ISSUE TITLE
go get fails '...but does not contain package github.com/shurcooL/go/ctxhttp'

### ISSUE THREAD

**Issue by klauern** [shurcooL/githubv4#56]
Attempting to `go get -u github.com/shurcooL/githubv4` and it fails:

```
go: finding github.com/shurcooL/graphql latest
go: finding github.com/shurcooL/go latest
../../../go/pkg/mod/github.com/shurcoo!l/graphql@v0.0.0-20180223021221-8d3d310716de/graphql.go:10:2: module github.com/shurcooL/go@latest found (v0.0.0-20191216061654-b114cc39af9f), but does not contain package github.com/shurcooL/go/ctxhttp
```

**Comment by dmitshur** [comment]
What's your `go env GOPROXY` value? Are you using a private proxy?

v0.0.0-20180223021221-8d3d310716de is an old version of module `github.com/shurcooL/graphql`. The latest version no longer imports package `github.com/shurcooL/go/ctxhttp`, see https://github.com/shurcooL/graphql/commit/16b88644589aaa174a21ae55cac72a9f60d5d837 from 2018.

**Comment by klauern** [comment]
Yeah, it must be that.  I unset the `GOPROXY` and it was able to download.  I'm not sure we even had this proxy in place that long, though.
