### ISSUE TITLE
Question: How to add a querystring as a variable?

### ISSUE THREAD

**Issue by superbeeny** [shurcooL/githubv4#59]
Hi,

Hopefully this is simple miss on my part.

```Go
	var query struct {
		Search struct {
			RepositoryCount int
			PageInfo        struct {
				EndCursor   githubv4.String
				HasNextPage bool
			}
			Repos []struct {
				Repository respository `graphql:"... on Repository"`
			} `graphql:"nodes"`
		} `graphql:"search(first: 100, after: $repocursor, type: REPOSITORY, query: $querystring)"`
		RateLimit struct {
			Cost      githubv4.Int
			Limit     githubv4.Int
			Remaining githubv4.Int
			ResetAt   githubv4.DateTime
		}
	}

	variables := map[string]interface{}{
		"repocursor":  (*githubv4.String)(nil),
		"querystring": githubv4.String(`\"archived: false pushed:>2020-04-01 created:2020-01-01..2020-02-01\"`),
	}
```

What is the correct format/method to substitute in a querystring?

Thanks in advance

**Comment by dmitshur** [comment]
I'm not completely sure what you mean by "substitute"? Do you mean change its value?

Its value is provided in the `variables` map above. So, you can just modify it there:

```
variables["querystring"] = githubv4.String(`"archived: true"`)
```

Also see https://github.com/shurcooL/githubv4#arguments-and-variables.

**Comment by superbeeny** [comment]
when I put it into the graphql query like
`		} graphql:"search(first: 100, after: $repocursor, type: REPOSITORY, query: \"pushed:>2020-04-01 created:2020-01-01..2020-02-01\")"`

I get results, when I choose to use a variable `$querystring` and variable in
`graphql:"search(first: 100, after: $repocursor, type: REPOSITORY, query: $querystring)"`

I get nothing.

**Comment by dmitshur** [comment]
Oh. It might be because you're including double quotes in the string in the latter case (but not in the former). Try:

```Go
variables["querystring"] = githubv4.String(`pushed:>2020-04-01 created:2020-01-01..2020-02-01`)
```

**Comment by superbeeny** [comment]
That was it thanks!
