### ISSUE TITLE
Custom request URL

### ISSUE THREAD

**Issue by xloem** [shurcooL/githubv4#82]
It would be nice to request from other hosts than api.github.com .

This means other hosts could offer the API REST interface.

**Comment by dmitshur** [comment]
You can specify a custom GraphQL endpoint URL with [`githubv4.NewEnterpriseClient`](https://pkg.go.dev/github.com/shurcooL/githubv4#NewEnterpriseClient). Is that what this issue is asking about?

**Comment by xloem** [comment]
I _think_ so.  Thank you.  Sorry I did not see that.
