### ISSUE TITLE
PR to add go.mod has not been merged

### ISSUE THREAD

**Issue by pddg** [shurcooL/githubv4#88]
The PR to add go.mod ( #69  ) has been approved. However, it seems to have been left unmerged.
It seems that the PR to add go.mod in  shurcooL/graphql, which is a dependency of this, is approved but is not merged as well.

What is the current status of these?

**Comment by dmitshur** [comment]
An initial go.mod file was added in commit 095e54f8d08f48f2d886d983114bf5fec9c16ad3. Thanks.
