### ISSUE TITLE
Code regeneration

### ISSUE THREAD

**Issue by jtyr** [shurcooL/githubv4#97]
I'm waiting for the code regeneration to cover some changes to the schema that I require to fix https://github.com/integrations/terraform-provider-github/issues/1005. Please could you regenerate the code or add GitHub Action to regenerate the code from latest schema on regular basis? Also tagging the code upon change/regeneration would be useful.

**Comment by dmitshur** [comment]
Sure, I'll regenerate today. I'm not ready to start making tags here yet, that will happen later.
